"""Model card generation functionality."""

from datetime import datetime
from pathlib import Path
from typing import Any


def generate_model_card(
    model_id: str,
    output_dir: Path,
    benchmark_results: dict[str, dict[str, Any]],
    quant_levels: list[str],
) -> Path:
    """Generate a Markdown model card with benchmark results table.

    Args:
        model_id: Original HuggingFace model ID.
        output_dir: Directory to save the model card.
        benchmark_results: Dictionary mapping model names to benchmark results.
        quant_levels: List of quantization levels used.

    Returns:
        Path to generated model card.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    card_path = output_dir / "MODEL_CARD.md"

    # Generate markdown content
    lines = [
        f"# {model_id.split('/')[-1]} GGUF Quantization Results",
        "",
        "> 🤖 **Made Autonomously Using [NEO](https://heyneo.com)** — Your Autonomous AI Engineering Agent",
        ">",
        "> [![VS Code Extension](https://img.shields.io/badge/VS%20Code-Install%20NEO-007ACC?logo=visualstudiocode&logoColor=white)](https://marketplace.visualstudio.com/items?itemName=NeoResearchInc.heyneo) [![Cursor Extension](https://img.shields.io/badge/Cursor-Install%20NEO-000000?logo=cursor&logoColor=white)](https://marketplace.cursorapi.com/items/?itemName=NeoResearchInc.heyneo)",
        "",
        f"Generated: {datetime.now().isoformat()}",
        "",
        "## Model Information",
        "",
        f"- **Original Model**: [{model_id}](https://huggingface.co/{model_id})",
        f"- **Quantization Levels**: {', '.join(quant_levels)}",
        "",
        "## Benchmark Results",
        "",
        generate_markdown_table(benchmark_results),
        "",
        "## Quantization Details",
        "",
        "| Quant Type | Description | Use Case |",
        "|------------|-------------|----------|",
        "| Q2_K | 2-bit K-quants, aggressive compression | Edge/mobile, very limited RAM |",
        "| Q4_K_M | 4-bit K-quants medium, balanced quality/size | General purpose, recommended |",
        "| Q5_K_S | 5-bit K-quants small, better quality | Quality-critical applications |",
        "| Q8_0 | 8-bit quantization, highest fidelity | Maximum quality, reference |",
        "",
        "## Files",
        "",
    ]

    # Add file list
    for quant_type in quant_levels:
        filename = f"{model_id.split('/')[-1]}-{quant_type}.gguf"
        lines.append(f"- `{filename}`")

    lines.extend([
        "",
        "## Usage",
        "",
        "### llama-server (Recommended)",
        "",
        "Start an OpenAI-compatible API server:",
        "",
        "```bash",
        "# Q2_K - Edge/Mobile deployment",
        f"llama-server -m {model_id.split('/')[-1]}-Q2_K.gguf -c 4096 --host 0.0.0.0 --port 8080",
        "",
        "# Q4_K_M - Balanced quality/size (Recommended)",
        f"llama-server -m {model_id.split('/')[-1]}-Q4_K_M.gguf -c 4096 --host 0.0.0.0 --port 8080",
        "",
        "# Q5_K_S - Better quality",
        f"llama-server -m {model_id.split('/')[-1]}-Q5_K_S.gguf -c 4096 --host 0.0.0.0 --port 8080",
        "",
        "# Q8_0 - Highest fidelity",
        f"llama-server -m {model_id.split('/')[-1]}-Q8_0.gguf -c 4096 --host 0.0.0.0 --port 8080",
        "```",
        "",
        "### Interactive Mode",
        "",
        "```bash",
        f"llama-cli -m {model_id.split('/')[-1]}-Q4_K_M.gguf -p \"Hello, world!\"",
        "```",
        "",
        "---",
        "Generated by QWEN36GGUF Pipeline",
    ])

    content = "\n".join(lines)
    card_path.write_text(content)

    return card_path


def generate_markdown_table(benchmark_results: dict[str, dict[str, Any]]) -> str:
    """Generate a Markdown table from benchmark results.

    Args:
        benchmark_results: Dictionary mapping model names to benchmark results.

    Returns:
        Markdown table string.
    """
    if not benchmark_results:
        return "No benchmark results available."

    # Extract column names from first result; drop the redundant "model" key
    # (the dict mirror of the row-key) so it doesn't appear twice in the table.
    first_result = next(iter(benchmark_results.values()))
    metric_keys = [k for k in first_result if k != "model"]
    columns = ["Model", *metric_keys]

    # Build header
    header = "| " + " | ".join(columns) + " |"
    separator = "|" + "|".join([" --- " for _ in columns]) + "|"

    # Build rows
    rows = []
    for model_name, results in sorted(benchmark_results.items()):
        row_values = [model_name]
        for col in metric_keys:
            value = results.get(col, "N/A")
            if value is None:
                value = "N/A"
            elif isinstance(value, float):
                value = f"{value:.4f}" if value < 100 else f"{value:.2f}"
            row_values.append(str(value))
        rows.append("| " + " | ".join(row_values) + " |")

    return "\n".join([header, separator] + rows)
