"""HuggingFace export bundle assembly.

Materializes a self-contained, ready-to-push HF repo folder under
`<output_dir>/hf_export/` containing:
- README.md  (HF model card with YAML frontmatter)
- .gitattributes  (Git LFS rule for *.gguf)
- the GGUF files themselves (hard-linked when on the same filesystem,
  copied otherwise)
"""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import Any

from qwen36gguf.card import generate_markdown_table

logger = logging.getLogger(__name__)


GITATTRIBUTES_LFS = "*.gguf filter=lfs diff=lfs merge=lfs -text\n"


def generate_hf_readme(
    model_id: str,
    benchmark_results: dict[str, dict[str, Any]],
    quant_levels: list[str],
    license_str: str = "mit",
) -> str:
    """Build the README.md content for the hf_export bundle.

    Includes YAML frontmatter (license, tags, base_model) and the same
    metric/usage sections as MODEL_CARD.md so the HF repo page renders
    correctly.

    Args:
        model_id: Source HuggingFace model id (e.g., ``Qwen/Qwen3.6-27B``).
        benchmark_results: Mapping of GGUF filename to metric dict.
        quant_levels: Quant types built in this run (e.g., ``["Q2_K", "Q4_K_M", ...]``).
        license_str: SPDX-style license string for the YAML frontmatter.

    Returns:
        The README.md content as a string.
    """
    short_name = model_id.split("/")[-1]

    frontmatter = [
        "---",
        f"license: {license_str}",
        f"base_model: {model_id}",
        "library_name: gguf",
        "tags:",
        "- gguf",
        "- quantized",
        "- llama.cpp",
        f"- {short_name.lower()}",
        "---",
        "",
    ]

    body = [
        f"# {short_name} — GGUF Quantizations",
        "",
        "> 🤖 **Made Autonomously Using [NEO](https://heyneo.com)** — Your Autonomous AI Engineering Agent",
        ">",
        "> [![VS Code Extension](https://img.shields.io/badge/VS%20Code-Install%20NEO-007ACC?logo=visualstudiocode&logoColor=white)](https://marketplace.visualstudio.com/items?itemName=NeoResearchInc.heyneo) [![Cursor Extension](https://img.shields.io/badge/Cursor-Install%20NEO-000000?logo=cursor&logoColor=white)](https://marketplace.cursorapi.com/items/?itemName=NeoResearchInc.heyneo)",
        "",
        f"Quantized GGUF variants of [`{model_id}`](https://huggingface.co/{model_id}) "
        "produced with [llama.cpp](https://github.com/ggerganov/llama.cpp).",
        "",
        "## Benchmark Results",
        "",
        generate_markdown_table(benchmark_results),
        "",
        "## Quantization Details",
        "",
        "| Quant Type | Description | Use Case |",
        "|------------|-------------|----------|",
        "| Q2_K | 2-bit K-quants, aggressive compression | Edge / mobile, very limited RAM |",
        "| Q4_K_M | 4-bit K-quants medium, balanced quality / size | General purpose, recommended |",
        "| Q5_K_S | 5-bit K-quants small, better quality | Quality-critical applications |",
        "| Q8_0 | 8-bit, near-lossless | Maximum fidelity, reference |",
        "",
        "## Files",
        "",
    ]

    for quant_type in quant_levels:
        body.append(f"- `{short_name}-{quant_type}.gguf`")

    body.extend([
        "",
        "## Usage",
        "",
        "Start an OpenAI-compatible server with one of the quants:",
        "",
        "```bash",
    ])
    for quant_type in quant_levels:
        body.append(
            f"llama-server -m {short_name}-{quant_type}.gguf -c 4096 --host 0.0.0.0 --port 8080"
        )
    body.extend([
        "```",
        "",
        "Or one-shot inference:",
        "",
        "```bash",
        f"llama-cli -m {short_name}-Q4_K_M.gguf -p \"Hello, world!\"",
        "```",
        "",
        "---",
        "Generated by [qwen36gguf](https://github.com/) pipeline.",
        "",
    ])

    return "\n".join(frontmatter + body)


def assemble_hf_export(
    output_dir: Path,
    model_id: str,
    gguf_paths: list[Path],
    benchmark_results: dict[str, dict[str, Any]],
    quant_levels: list[str],
    license_str: str = "mit",
) -> Path:
    """Materialize the hf_export bundle under ``output_dir / "hf_export"``.

    Layout produced::

        <output_dir>/hf_export/
        ├── README.md
        ├── .gitattributes
        └── <model>-<QUANT>.gguf  (one per gguf_path)

    Args:
        output_dir: Run output directory (e.g. ``out/<timestamp>/``).
        model_id: Source HuggingFace model id.
        gguf_paths: Paths to the quantized GGUF files to include.
        benchmark_results: Per-file benchmark metric dicts (used for README).
        quant_levels: Quant types present in this bundle.
        license_str: SPDX license string for the YAML frontmatter.

    Returns:
        Path to the ``hf_export/`` directory.
    """
    output_dir = Path(output_dir)
    bundle_dir = output_dir / "hf_export"
    bundle_dir.mkdir(parents=True, exist_ok=True)

    # README.md
    readme = generate_hf_readme(
        model_id=model_id,
        benchmark_results=benchmark_results,
        quant_levels=quant_levels,
        license_str=license_str,
    )
    (bundle_dir / "README.md").write_text(readme)

    # .gitattributes (LFS rule for *.gguf)
    (bundle_dir / ".gitattributes").write_text(GITATTRIBUTES_LFS)

    # GGUF files — hard-link when possible (same fs, instant, no extra space),
    # fall back to copy otherwise. Overwrite any existing entry.
    for src in gguf_paths:
        src = Path(src)
        if not src.exists():
            logger.warning("gguf source missing, skipping: %s", src)
            continue
        dst = bundle_dir / src.name
        if dst.exists():
            dst.unlink()
        try:
            os.link(src, dst)
        except OSError:
            shutil.copy2(src, dst)

    logger.info("Assembled hf_export bundle at %s", bundle_dir)
    return bundle_dir
